version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions-dependency:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
