cc_library(
    name = "sentence_extractor",
    hdrs = [
        "sentence_extractor.h",
    ],
    srcs = [
        "sentence_extractor.cc",
    ],
    deps = [
        "//third_party:podofo",
    ],
    visibility = ["//visibility:public"],
)
