cc_library(
    name = "calculators",
    hdrs = [
        "serialization_calculators.h",

    ],
    srcs = [
        "serialization_calculators.cc",

    ],
    deps = [
        "//src/image:serialization",
        "//src/mediapipe/inference:inference_calculators",
        "//src/mediapipe/inference:geti_calculator_base",
        "//src/mediapipe/inference:inference_utils",
    ],
    visibility = ["//visibility:public"],
    alwayslink=1
)
