package(default_visibility = ["//visibility:public"])

cc_library(
    name = "errors",
    hdrs = [
        "errors.h",
    ],
    deps = [
        ":status",
    ],
)

cc_library(
    name = "status",
    hdrs = [
        "status.h",
    ]
)
