cc_library(
    name = "sentence_transformer_pipeline",
    hdrs = [
        "sentence_transformer_pipeline.h",
    ],
    srcs = [
        "sentence_transformer_pipeline.cc",
    ],
    deps = [
        "//third_party:openvino",
    ],
    visibility = ["//visibility:public"],
)
