display_name: OpenVINO Test Drive
package_name: openvinotestdrive

maintainer:
  name: Ronald Hecker
  email: ronald.hecker@intel.com

priority: optional

section: x11

installed_size: 396000

dependencies:
  - libtbb12
  - libtiff5
  - libopenjp2-7
  - libpng16-16
  - libzstd1

essential: false

icon: images/logo_250.png

keywords:
  - OpenVINO
  - Inference

generic_name: OpenVINO Test Drive

categories:
  - Development
  - Utility

startup_notify: true
