name: Lint Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: {} # No permissions by default on workflow level

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Check License Header
        uses: apache/skywalking-eyes/header@b7f8b351c2db8005972712d7efc0a15484a15bcb

      - name: Set up Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos
