name: macOS build

on: push

jobs:
  build-macos-ui:
    name: Build macOS ui
    runs-on: macos-latest
    permissions:
      contents: write

    if: false

    steps:
      - uses: actions/checkout@v4
      - name: Set safe filename
        id: set_filename
        run: |
          SAFE_REF_NAME=${GITHUB_REF_NAME//\//_}
          echo "SANITIZED_FILENAME=OpenVINO-TestDrive-${SAFE_REF_NAME}-macos.zip" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.5'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ env.SANITIZED_FILENAME }}
          path: build/macos/Build/Products/Release
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SANITIZED_FILENAME }}
          path: build/macos/Build/Products/Release
      - name: macOS Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.SANITIZED_FILENAME }}