name: "Security scan"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run Zizmor scan
        uses: open-edge-platform/anomalib/.github/actions/security/zizmor@bbcd5b65aafb3674d7dd078a1556a104701a88c3
        with:
          scan-scope: "all"
          severity-level: "LOW"
          confidence-level: "LOW"
          fail-on-findings: false # reports only


  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run Trivy scan
        id: trivy
        uses: open-edge-platform/anomalib/.github/actions/security/trivy@bbcd5b65aafb3674d7dd078a1556a104701a88c3
        with:
          scan_type: "fs"
          scan-scope: all
          severity: LOW
          scanners: "vuln,secret,config"
          format: "sarif"
          timeout: "15m"
          ignore_unfixed: "false"
